ALTER TABLE `pending_registration`
  ADD COLUMN IF NOT EXISTS `consent_core` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS `consent_timestamp` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `privacy_notice_version` VARCHAR(50) NULL;

ALTER TABLE `user`
  ADD COLUMN IF NOT EXISTS `consent_core` BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS `consent_timestamp` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `privacy_notice_version` VARCHAR(50) NULL;

ALTER TABLE `alumni`
  MODIFY COLUMN `is_student_id_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_date_of_birth_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_email_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_phone_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_position_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_company_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_employment_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_location_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_social_links_public` BOOLEAN NOT NULL DEFAULT FALSE,
  MODIFY COLUMN `is_skills_public` BOOLEAN NOT NULL DEFAULT FALSE;
